### PR TITLE
DEV | Home Page Updates

### PR DESCRIPTION
**Pull request by sehmuzc**
Home page name has been updated and Spaces link has been added.

### CODE REVIEW

**Comment by SahinKapan** [comment]
Nice Work

**Comment by SahinKapan** [comment]
Nice Work

**Review by SahinKapan — APPROVED** [review]
Nice work again

**Comment by ceydaduzgec** [comment]
What is the purpose of uploads folder? If it is local uploads I think we shouldn't add them to repo, what do you think? @sehmuzc

**Comment by sehmuzc** [comment]
Hi Ceyda, it was already existing in the previous project, I did not make any changes in that section. You can remove it.

**Pull request merged**
