### PR TITLE
DEV |Space feed page - Frontend

### PR DESCRIPTION
**Pull request by MariaAsif135**
### Description

html page has been created for the space feed page.

### CODE REVIEW

**Review by cemrekut — APPROVED** [review]
i fixed

**Comment by ceydaduzgec** [comment]
You need to resolve conflicts before merging it to the `dev`. If you don't know how to do it I can help you with that.

**Comment by cemrekut** [comment]
> You need to resolve conflicts before merging it to the `dev`. If you don't know how to do it I can help you with that.

hi Ceyda, it would be great, generally the system gives this error.

**Comment by ceydaduzgec** [comment]
Hey, could you first watch this: https://www.youtube.com/watch?v=mOJazBNrG-c
The most important part is to decide which version should be the current one. 
For the next branch you are creating make sure that I is created from `dev`and once in a while do `git merge origin/dev` to make sure your branch is up to date. If you have questions after the video we can go over it tomorrow at the class time.

**Pull request closed without merging**
