### PR TITLE
DEV |  Made sidebar responsive

### PR DESCRIPTION
**Pull request by SahinKapan**
### Description

- The html has been corrected so that the sidenav and the main content are intertwined. Create space form has been edited.

### CODE REVIEW

**Comment by SahinKapan** [comment]
Screen Shot 2023-03-22 at 13 07 34

**Review by sehmuzc — APPROVED** [review]
Thanks for the front end updates.

**Comment by ceydaduzgec** [comment]
Could you also do the things that are written in the description and then delete it please @SahinKapan?

**Comment by SahinKapan** [comment]
> Could you also do the things that are written in the description and then delete it please @SahinKapan?

Is it correct now ?

**Comment by ceydaduzgec** [comment]
Yes thank you so much! Looks so decent. 💯  You can merge whenever you want.

**Comment by ceydaduzgec** [comment]
The development branch was broken. That's why it was failing. Fixed the development and merged again.

**Pull request merged**
