### PR TITLE
DEV | Fix space_initial.html

### PR DESCRIPTION
**Pull request by cemrekut**

### CODE REVIEW

**Comment by cemrekut** [comment]
@ceydaduzgec Ceyda i add some features in recommendation space. But i can't send it. Can you help me

**Comment by ceydaduzgec** [comment]
Sure thing! There were some things missing. 
1- There were conflicts between `dev` and your `branch`. I resolved it but I can show you how to resolve it on your own in our next meeting.
2- The name of the pull request should start with the branch you want to merge into. In our case it is `dev` so the name of the pull request should be: `DEV | Feature specifics`
3- You should always assign reviewer and assignee.
4- Also adding label, project and milestone is a good practice.
5- Lastly, you should make sure that the github checks are passed. 
For linter you can read more on -> `docs/linting.md`

**Comment by cemrekut** [comment]
> 

thank you so much

**Review by ceydaduzgec — APPROVED** [review]
And someone should check your code and give an approval. Now we are ready to merge. You can click on the green merge button whenever you want.

**Pull request merged**
