### PR TITLE
DEV | Fixed 'Create Space' button functionality

### PR DESCRIPTION
**Pull request by SahinKapan**
### Description

- Create space page has been rearranged and functions have been brought back.

### CODE REVIEW

**Comment by SahinKapan** [comment]
image
image

**Review by sehmuzc — COMMENTED** [review]
Why are there migrations with the front-end changes, could you please get the latest version of DEV environment and only include the create_space html changes?

**Comment by ceydaduzgec** [comment]
@sehmuzc I think they are related with Django being 3.2 like mentioned here: https://docs.djangoproject.com/en/3.2/releases/3.2/
But we already have `DEFAULT_AUTO_FIELD` in our settings so I will keep investigating the reason for unnecessary migrations.

**Comment by SahinKapan** [comment]
This pull request isn't necessary anymore.

**Pull request closed without merging**
